<div class="row">

    <?php if ($this->pictures > 0): ?>

        <?php foreach ($this->pictures as $picture): ?>
            <div class="caption col-md-3">

                <?php $dir = Zend_Registry::get('config')->md->dir; ?>
                <img class="img-thumbnail"  alt="" src="<?= "{$dir}/". $this->escape(trim($picture)); ?>">

            </div>

        <?php endforeach; ?>

    <?php else: ?>
        <div class="col-md-12">
            <div class="well">
                <?php echo $this->translate('not have products'); ?>
            </div>

        </div>
    <?php endif; ?>

</div>