<?php if ($this->products > 0): ?>
    <table class="table table-hover">
        <!--заголовок-->
        <?= $this->partial('/product/row/product-tr.phtml', array('ishead' => true)); ?>

        <?php foreach ($this->products as $k => $p): ?>

            <!--рядок товару-->
            <?php $p['num-row'] = $k + 1; ?>
            <?= $this->partial('/product/row/thumbnail.phtml', array('product' => $p)); ?>

        <?php endforeach; ?>

    </table>
<?php else: ?>

    <p>
        <?php echo $this->translate('not have products'); ?>
    </p>

<?php endif; ?>