<?php if ($this->products > 0): ?>
    <table class="table table-hover">
        <!--заголовок-->
        <tr class="active">
            <td><?= $this->translate('number'); ?></td>
            <td><?= $this->translate('picture'); ?></td>
            <td><?= $this->translate('name'); ?></td>
            <td><?= $this->translate('description'); ?></td>
            <td><?= $this->translate('galeries'); ?></td>
            <td><?= $this->translate('admin-panel'); ?></td>
        </tr>
        <?php foreach ($this->products as $k => $p): ?>

            <!--рядок товару-->
            <?php $p['num-row'] = $k + 1; ?>
            <?= $this->partial('/product/row/product-tr.phtml', array('product' => $p)); ?>

        <?php endforeach; ?>

    </table>
<?php else: ?>

    <p>
        <?php echo $this->translate('not have products'); ?>
    </p>

<?php endif; ?>