<?= $this->partial('/section/jumbotron.phtml', array('title'=> $this->translate('Contacts'))); ?>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
<!--                --><?//= $this->partial('/index/contacts/form.phtml'); ?>
                <?= $this->form ?>
            </div>
        </div>
    </div>
</div>