<div class="jumbotron snenko-color">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <h1 class="nice-font"><?= $this->translate('label'); ?></h1>
                <p class="head-descr nice-font"><?= $this->translate('sublabel'); ?></p>
                <a href="<?php echo $this->url(array(), 'gallery-index'); ?>"
                   class="btn btn-outline-inverse btn-lg ">
                    <?= $this->translate('Learn more') ?>
                    <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                </a>

            </div>
        </div>
    </div>

</div>

<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <?= $this->partial('/index/blocks/carusel.phtml', array('carousel' => $this->carousel)); ?>
            </div>
            <div class="col-md-4">
                <?= $this->partial('/index/blocks/right-panel.phtml', array('articles' => $this->articles)); ?>
            </div>
        </div>
    </div>
</div>

<!-- Products -->
<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"><?= $this->translate('My products') ?></h3>
                    </div>

                    <div class="panel-body">

                        <?= $this->partial('/index/blocks/products.phtml', array('products' => $this->products)); ?>

                    </div>

                    <div class="panel-footer">
                        <a class="btn btn-lg btn-outline"
                           href="<?php echo $this->url(array(), 'gallery-index'); ?>"
                           role="button">
                            <?= $this->translate('Learn more') ?>
                            <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
                        </a>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>