<?php IF($this->key==1): ?>
    <div class="clearfix visible-xs-block"></div>
<?php ELSEIF($this->key==2): ?>
    <div class="clearfix visible-sm-block"></div>
<?php ELSEIF($this->key==3): ?>
    <div class="clearfix visible-xs-block visible-md-block visible-lg-block"></div>
<?php ELSEIF($this->key==4): ?>
    <div class="clearfix visible-sm-block"></div>
<?php ELSEIF($this->key==6): ?>
<!--    <div class="clearfix visible-sm-block"></div>-->
<?php ELSEIF($this->key==9): ?>
    <!--<div class="clearfix visible-xs-block visible-sm-block visible-md-block visible-lg-block"></div>-->
<?php ENDIF; ?>

