<!--<div class="row">-->
<?php IF ($this->products): ?>

    <div class="container">
        <div class="wrapper">
            <h1 class="the-head">Our Food</h1>

            <div class="row-fluid">
                <div class="span12">
                    <div class="scrollbar">
                        <div class="handle" style="transform: translateZ(0px) translateX(442px); width: 618px;">
                            <div class="mousearea"></div>
                        </div>
                    </div>

                    <div class="frame effects" id="the-portfolio" style="overflow: hidden;">
                        <ul class="clearfix" style="transform: translateZ(0px) translateX(-1123px); width: 2080px;">
                            <li><img src="images/food1.png" alt=""></li>
                            <li><img src="images/food2.png" alt=""></li>
                            <li class=""><img src="images/food3.png" alt=""></li>
                            <li class=""><img src="images/food4.png" alt=""></li>
                            <li class=""><img src="images/food5.png" alt=""></li>
                            <li class=""><img src="images/food6.png" alt=""></li>
                            <li class="active"><img src="images/food7.png" alt=""></li>
                            <li class=""><img src="images/food8.png" alt=""></li>
                        </ul>
                    </div>

                    <div class="controls center">
                        <button class="prev"><i class="icon-double-angle-left"></i></button>
                        <button class="next"><i class="icon-double-angle-right"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>

<?php ENDIF; ?>
<!--</div>-->