<div class="row">
    <?php IF ($this->products): ?>
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ol class="carousel-indicators">
                <?php FOREACH ($this->products as $key => $value): ?>
                    <?php $active=($key==0)?'active':''; ?>
                    <li data-target="#carousel-example-generic" data-slide-to="<?= $key ?>" class="<?= $active?>"></li>
                <?php ENDFOREACH; ?>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">

                <?php FOREACH ($this->products as $key => $product): ?>

                    <?php $active=($key==0)?' active':''; ?>

                    <?php $picture = '/photos/'.$product['pictures'][0]; ?>

                    <div class="item <?=$active; ?>" style="margin: auto">

                        <img class="img-responsive"
                             src="<?= $picture ?>"
                             alt="<?= $product['description'] ?>">

                        <div class="carousel-caption">
                            <?= $product['name'] ?>
                        </div>
                    </div>

                <?php ENDFOREACH; ?>

            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>
    <?php ENDIF; ?>
</div>