<?= $this->partial('/section/jumbotron.phtml', array('title'=> $this->translate('Products'))); ?>

<div class="section">
    <div class="container">
        <div class="row">
            <?= $this->partial('/product/row/product-admin-panel.phtml'); ?>
        </div>
        <div class="row">
            <div class="col-md-12">
<?= $this->partial('/product/row/thumbnails.phtml', array('products' => $this->products)); ?>
<?//= $this->partial('/product/row/product-table.phtml', array('products' => $this->products)); ?>
            </div>
        </div>
    </div>
</div>