<?php foreach ($this->container as $page) { ?>
    <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>
    <?php // when using partials we need to manually check for ACL conditions ?>

    <?php if (!$page->isVisible() || !$this->navigation()->accept($page)) {
        continue;
    } ?>

    <?php $hasChildren = $page->hasPages(); ?>
    <?php if (!$hasChildren) { ?>

        <li>
            <a href="<?php echo $page->getHref() ?>">
                <?= $this->partial('navbar/span.phtml', array('span' => $page->toArray()['span'],)); ?>
                <?= $this->partial('navbar/ico.phtml', array('ico' => $page->toArray()['ico'],)); ?>
                <?php echo $this->translate($page->getLabel()) ?>
            </a>
        </li>

    <?php } else { ?>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <?= $this->partial('navbar/span.phtml', array('span' => $page->toArray()['span'],)); ?>
                <?= $this->partial('navbar/ico.phtml', array('ico' => $page->toArray()['ico'],)); ?>
                <?php echo $this->translate($page->getLabel()) ?>
                <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <?php foreach ($page->getPages() as $child) { ?>

                    <?php // when using partials we need to manually check for ACL conditions ?>
                    <?php if (!$child->isVisible() || !$this->navigation()->accept($child)) {
                        continue;
                    } ?>
                    <li>
                        <a href="<?php echo $child->getHref() ?>">
                            <?= $this->partial('navbar/span.phtml', array('span' => $child->toArray()['span'],)); ?>
                            <?= $this->partial('navbar/ico.phtml', array('ico' => $child->toArray()['ico'],)); ?>
                            <?php echo $this->translate($child->getLabel()) ?>
                        </a>
                    </li>

                <?php } ?>
            </ul>
        </li>

    <?php } ?>

<?php } ?>