<form id="my-contact-form" action="/settings" method="post" class="form-horizontal"novalidate="true"  role="form">
    <div><input name="my-contact-form" type="hidden" value="1"  class="form-control"></div>
    <fieldset>
        <legend>Please fill in this form to contact us</legend>
        <div class="form-group">
            <label for="username" class="col-sm-4 control-label">Your name <sup class="text-danger">* </sup>: </label>
            <div class="col-sm-8">
                <input id="username" name="username" type="text" value="" required="required" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="useremail" class="col-sm-4 control-label">Your email <sup class="text-danger">* </sup>: </label>
            <div class="col-sm-8">
                <input id="useremail" name="useremail" type="email" value="" required="required" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="userphone" class="col-sm-4 control-label">Your phone <sup class="text-danger">* </sup>: </label>
            <div class="col-sm-8">
                <input id="userphone" name="userphone" type="text" value="" required="required" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <label for="subject" class="col-sm-4 control-label">Subject : </label>
            <div class="col-sm-8">
                <select id="subject" name="subject"  class="form-control">
                    <option value="Support" >Support</option>
                    <option value="Sales" >Sales</option>
                    <option value="Other" >Other</option>
                </select>
            </div>
        </div>
        <div class="form-group">
            <label for="message" class="col-sm-4 control-label">Your message <sup class="text-danger">* </sup>: </label>
            <div class="col-sm-8">
                <textarea id="message" name="message" cols="30" rows="4" required="required" class="form-control"></textarea>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-4 control-label">Suscribe to Newsletter :</label>
            <div class="col-sm-8">
                <label class="checkbox-inline"><input type="checkbox" id="newsletter" name="newsletter" value="1" checked="checked"></label>
            </div>
        </div>
        <div class="form-group">
            <label for="captcha" class="col-sm-4 control-label">Type the characters please :</label>
            <div class="col-sm-8">
                <input id="captcha" name="captcha" type="text" value="" size="15" class="form-control">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <button type="submit" name="submit-btn" value="1" class="btn btn-success">Submit</button>
            </div>
        </div>
    </fieldset>
</form>

<script src="http://localhost/modelehtml5/DOCS/phpforms/plugins/jquery-realperson/jquery.realperson.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#captcha").realperson();
    });
</script>