<?php IF ($this->carousel): ?>
    <div class="thumbnail">
        <div id="carousel-generic" class="carousel slide" data-ride="carousel">

            <!-- Indicators -->
            <ol class="carousel-indicators">
                <?php FOREACH ($this->carousel as $key => $value): ?>
                    <?php $active = ($key == 0) ? 'active' : ''; ?>
                    <li data-target="#carousel-example-generic" data-slide-to="<?= $key ?>" class="<?= $active ?>"></li>
                <?php ENDFOREACH; ?>
            </ol>

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">

                <?php FOREACH ($this->carousel as $key => $c): ?>

                    <?php $active = ($key == 0) ? ' active' : ''; ?>

                    <?php $picture = '/photos/' . $c['picture']; ?>

                    <div class="item <?= $active; ?>" style="margin: auto; text-align: center">

                        <img class="img-responsive"
                             src="<?= $picture ?>"
                             alt="<?= $c['description'] ?>">

                        <?php $url = (!$c['url'] && $c['productid'])?$url= $this->url(array('id' => $c['productid']), 'product-display'):$c['url']; ?>

                        <div class="carousel-caption">
                            <a href="<?= $url ?>">
                                <?= $c['title'] ?>
                            </a>
                        </div>

                    </div>

                <?php ENDFOREACH; ?>

            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>

        </div>
    </div>
<?php ENDIF; ?>
