<?php $num = 0; ?>
<table class="table table-bordered">
    <tr>
        <td>№</td>
        <td><?= $this->translate('label') ?></td>
        <td><?= $this->translate('russian') ?></td>
        <td><?= $this->translate('ukrainian') ?></td>
        <td><?= $this->translate('english') ?></td>
        <td></td>
    </tr>

    <?php FOREACH ($this->translations as $label => $transl): ?>

        <tr>
            <td><?= $num++; ?></td>
            <td><?= $label ?></td>
            <td><?= $transl['ru'] ?></td>
            <td><?= $transl['uk'] ?></td>
            <td><?= $transl['en'] ?></td>
            <td>
                <a href="<?php echo $this->url(array('label' => $label), 'translator-update', true); ?>">
                    <?= $this->translate('update') ?>
                </a>
            </td>
        </tr>

    <?php ENDFOREACH; ?>
</table>