<?php IF (Acl::getInstance()->getCurrentRole() == Acl::ROLE_ADMIN): ?>
    <div class="page-header">
        <h2><?= $this->translate('Not active records') ?></h2>
    </div>

    <div class="btn-group" role="group">

        <?php IF ($this->blogid): ?>

            <?php $url_edit = $this->url(array('id' => $this->blogid), 'blog-update'); ?>
            <?php $url_delete = $this->url(array('id' => $this->blogid), 'blog-delete'); ?>

            <a class="btn btn-warning" href="<?= $url_edit; ?>" title="<?= $this->translate('blog-update'); ?>">
                <span class="glyphicon glyphicon-pencil"></span><?= $this->translate('blog-update'); ?>
            </a>
            <a class="btn btn-danger" href="<?= $url_delete; ?>" title="<?= $this->translate('blog-delete'); ?>">
                <span class="glyphicon glyphicon-remove"></span><?= $this->translate('blog-delete'); ?>
            </a>

        <?php ELSE: ?>
            <?php $url_prod_create = $this->url(array(), 'blog-create'); ?>

            <a class="btn btn-danger" href="<?= $url_prod_create; ?>">
                <?= $this->translate('blog-create'); ?>
            </a>

        <?php ENDIF; ?>

    </div>

<?php ENDIF; ?>
