<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                <?php IF($this->title): ?>
                    <div class="page-header">
                        <h1><?= $this->title ?></h1>
                    </div>
                <?php ENDIF; ?>

                <?= $this->form; ?>

            </div>
        </div>
    </div>
</div>