<?= $this->partial('/section/jumbotron.phtml', array('title'=>$this->escape($this->gallery['galleryname']))); ?>

<div class="section">
    <div class="container">
        <div class="row">

            <div class="col-md-12">

                <?= $this->partial('/product/row/product-admin-panel.phtml');?>

                <?= $this->partial('/gallery/row/thumbnail-products.phtml', array('products' => $this->products)); ?>

            </div>
        </div>
    </div>
</div>






