<?php $this->dojo()->enable()->setDjConfigOption('parseOnLoad', true)->requireModule("dijit.layout.AccordianContainer")->requireModule("dijit.layout.ContentPane");?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h2><?= $this->blog['title']; ?></h2>
    </div>
    <div class="panel-body">
        <?= $this->partial('/blog/row/blog-admin-panel.phtml', array('blogid' => $this->blog['blogid'])); ?>
        <article>
            <?= $this->blog['body'] ?>
        </article>
        <?= $this->partial('/blog/row/mask.phtml', array('mask' => $this->blog['mask'])); ?>
    </div>
    <div class="panel-footer">
        <?= $this->dateFormat($this->blog['blogupdate'], 'dd MMM YYYY hh:mm'); ?>
    </div>
</div>