<?php // setup required dojo elements:

$this->dojo()->enable()
    ->setDjConfigOption('parseOnLoad', true)

    ->requireModule("dijit.layout.AccordianContainer")
    ->requireModule("dijit.layout.ContentPane")
?>

<div class="page-header">
    <h2><?= $this->translate('Blog') ?></h2>
</div>

<?= $this->partial('/blog/row/blog-admin-panel.phtml'); ?>
<?= $this->partial('/blog/row/blogs.phtml', array('blogs' => $this->blogs)); ?>

<!--adminka-->
<div class="page-header">
    <h2><?= $this->translate('Not active records') ?></h2>
</div>

<?= $this->partial('/blog/row/blogs.phtml', array('blogs' => $this->blogs_status_none)); ?>
