<?php // setup required dojo elements:

$this->dojo()->enable()
    ->setDjConfigOption('parseOnLoad', true)

    ->requireModule("dijit.layout.AccordianContainer")
    ->requireModule("dijit.layout.ContentPane")
?>

<?= $this->partial('/section/jumbotron.phtml', array('title'=> $this->translate('Blog'))); ?>


<div class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <?= $this->partial('/blog/row/blog-admin-panel.phtml'); ?>
                <?= $this->partial('/blog/row/blogs.phtml', array('blogs' => $this->blogs)); ?>
            </div>
        </div>
        <?php IF(Acl::getInstance()->getCurrentRole() == Acl::ROLE_ADMIN): ?>
            <div class="row">
                <div class="col-md-12">
                    <?= $this->partial('/blog/row/blogs.phtml', array('blogs' => $this->blogs_status_none)); ?>
                </div>
            </div>
        <?php ENDIF; ?>

    </div>
</div>
